# Generated by Django 5.1.2 on 2025-02-01 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particulars', models.CharField(max_length=255)),
                ('opening', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receipt', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('signed_by', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
